2025-03-21 16:01:38,102 - ERROR -   File "e:\research\envs\PGRWQ\lib\threading.py", line 917, in run
2025-03-21 16:01:38,105 - ERROR - self._target(*self._args, **self._kwargs)
2025-03-21 16:01:38,105 - ERROR -   File "D:\PGRWQ\src_PGRWQ\main.py", line 133, in _monitor_file
2025-03-21 16:01:38,105 - ERROR - log_dir = "."
2025-03-21 16:01:38,106 - ERROR - FileNotFoundError
2025-03-21 16:01:38,106 - ERROR - :
2025-03-21 16:01:38,106 - ERROR - [Errno 2] No such file or directory: 'logs\\gpu_memory_log.csv'
